# Generated by Django 4.2.1 on 2023-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=500)),
                ('Agenda', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=150)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
